### ISSUE TITLE
Change in collection method

### ISSUE THREAD

**Issue by lmroz** [intelsdi-x/snap-plugin-collector-node-manager#14]
In https://github.com/intelsdi-x/snap-plugin-collector-node-manager/commit/70fc4ce6e173df64503ffdaf2ca2a4d74246dfae communication with IPMI is done using ipmitool. Previous mothod using direct calls to device driver is sillently dropped. Readme file doesn't mentoin that nor it's mentioned that additional system requirement is ipmitool installed on monitored platform.

**Comment by PatrykMatyjasek** [comment]
Fixed with https://github.com/intelsdi-x/snap-plugin-collector-node-manager/pull/15
